/*
Script de análisis de créditos del sistema financiero

Este script incluye:
- Creación de vistas analíticas
- Cálculo de métricas de crecimiento
- Análisis de riesgo (morosidad)
- Indicadores de rentabilidad y solidez

Requisitos:
- Base de datos con tabla 'creditos_sbs', creada previamente con el script de limpieza de datos.
*/

--VISUALIZACION TABLA COMPLETA 
SELECT * FROM creditos_sbs;

--CRECIMIENTO DEL SISTEMA FINANCIERO
--EVOLUCION DE CREDITOS TOTALES POR AÑO
CREATE OR ALTER VIEW VW_CREDITOS_TOTALES AS
SELECT 
	YEAR(FECHA) AS ANIO,
	SUM(
		ISNULL(CREDITOS_CONSUMO, 0)+
		ISNULL(CREDITOS_HIPOTECARIOS, 0)+
		ISNULL(CREDITOS_CORPORATIVOS,0)+
		ISNULL(CREDITOS_MEDIANAS, 0)+
		ISNULL(CREDITOS_PEQUENAS, 0)+
		ISNULL(CREDITOS_MICROEMPRESAS, 0)
	) AS CREDITOS_TOTALES, 

	AVG(MOROSIDAD) AS MOROSIDAD_PROMEDIO_ANUAL, 
	AVG(ROE) AS ROE_PROMEDIO_ANUAL, 
	AVG(ROA) AS ROA_PROMEDIO_ANUAL,
	AVG(RATIO_CAPITAL_GLOBAL) AS RATIO_CAPITAL_PROMEDIO_ANUAL

FROM creditos_sbs
GROUP BY YEAR(FECHA);

SELECT * FROM VW_CREDITOS_TOTALES

--EVOLUCION DE CREDITOS TOTALES POR MES
CREATE OR ALTER VIEW VW_CREDITOS_TOTALES_MENSUALES AS
SELECT 
	FECHA,
	SUM(
		ISNULL(CREDITOS_CONSUMO, 0)+
		ISNULL(CREDITOS_HIPOTECARIOS, 0)+
		ISNULL(CREDITOS_CORPORATIVOS,0)+
		ISNULL(CREDITOS_MEDIANAS, 0)+
		ISNULL(CREDITOS_PEQUENAS, 0)+
		ISNULL(CREDITOS_MICROEMPRESAS, 0)
	) AS CREDITOS_TOTALES, 

	AVG(MOROSIDAD) AS MOROSIDAD_PROMEDIO_MENSUAL, 
	AVG(ROE) AS ROE_PROMEDIO_MENSUAL, 
	AVG(ROA) AS ROA_PROMEDIO_MENSUAL,
	AVG(RATIO_CAPITAL_GLOBAL) AS RATIO_CAPITAL_PROMEDIO_MENSUAL

FROM creditos_sbs
GROUP BY FECHA;

SELECT * FROM VW_CREDITOS_TOTALES_MENSUALES

--CRECIMIENTO INTERANUAL
CREATE OR ALTER VIEW VW_CRECIMIENTO_CREDITOS_ANUALES
AS
WITH CREDITOS_ANUALES AS (
	SELECT 
		YEAR(FECHA) AS ANIO, 
		SUM(
			ISNULL(CREDITOS_CONSUMO, 0)+
			ISNULL(CREDITOS_HIPOTECARIOS, 0)+
			ISNULL(CREDITOS_CORPORATIVOS,0)+
			ISNULL(CREDITOS_MEDIANAS, 0)+
			ISNULL(CREDITOS_PEQUENAS, 0)+
			ISNULL(CREDITOS_MICROEMPRESAS, 0)
		) AS CREDITOS_TOTALES
	FROM creditos_sbs
	GROUP BY YEAR(FECHA)
),
BASE AS (
	SELECT 
		ANIO,
		CREDITOS_TOTALES,
		LAG(CREDITOS_TOTALES) OVER (ORDER BY ANIO) AS TOTAL_PREVIO
	FROM CREDITOS_ANUALES
)

SELECT 
	ANIO,
	CREDITOS_TOTALES,
	TOTAL_PREVIO,
	(CREDITOS_TOTALES - TOTAL_PREVIO) * 100.0 / NULLIF(TOTAL_PREVIO,0)
	AS CRECIMIENTO_INTERANUAL
FROM BASE;

SELECT * FROM VW_CRECIMIENTO_CREDITOS_ANUALES

--VARIACION PORCENTUAL MENSUAL DE CREDITOS DE CONSUMO
SELECT FECHA, CREDITOS_CONSUMO, LAG(CREDITOS_CONSUMO) OVER (ORDER BY FECHA) AS MES_ANTERIOR,
(CREDITOS_CONSUMO - LAG(CREDITOS_CONSUMO) OVER (ORDER BY FECHA))*100.0 / NULLIF(LAG(CREDITOS_CONSUMO) OVER (ORDER BY FECHA),0) AS  VARIACION_PCT
FROM creditos_sbs;

--CRECIMIENTO TOTAL DE CREDITOS
WITH BASE AS (
    SELECT FECHA,
	TOTAL_CREDITOS =
            ISNULL(CREDITOS_CONSUMO,0) +
            ISNULL(CREDITOS_HIPOTECARIOS,0) +
            ISNULL(CREDITOS_CORPORATIVOS,0) +
            ISNULL(CREDITOS_MEDIANAS,0) +
            ISNULL(CREDITOS_PEQUENAS,0) +
            ISNULL(CREDITOS_MICROEMPRESAS,0)

    FROM creditos_sbs
),
EXTREMOS AS (
	SELECT TOP 1
		FIRST_VALUE(TOTAL_CREDITOS) OVER (ORDER BY FECHA)
		AS CREDITO_TOTAL_INICIAL,
		LAST_VALUE(TOTAL_CREDITOS) OVER 
		(ORDER BY FECHA	ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
		AS CREDITO_TOTAL_FINAL

		FROM BASE
)
SELECT *, 
	(CREDITO_TOTAL_FINAL-CREDITO_TOTAL_INICIAL)*100.0/
	NULLIF(CREDITO_TOTAL_INICIAL,0) AS CRECIMIENTO_TOTAL_PCT

FROM EXTREMOS;

--MAXIMO NIVEL DE CREDITOS
SELECT TOP 1
	FECHA,
	TOTAL_CREDITOS 
FROM VW_CREDITOS_TOTALES_MENSUALES
ORDER BY CREDITOS_TOTALES DESC;

-- PERIODOS DE MAYOR CRECIMIENTO
SELECT TOP 10 FECHA, CREDITOS_CONSUMO, CREDITOS_CONSUMO - LAG(CREDITOS_CONSUMO) OVER (ORDER BY FECHA) AS CRECIMIENTO
FROM creditos_sbs
ORDER BY CRECIMIENTO DESC;

-----------------------------------------------------------------------------------------------------------

--PEOR PERIODO FINANCIERO - TENDENCIA DE RIESGO
--EVOLUCION DE MOROSIDAD
SELECT FECHA, MOROSIDAD 
FROM creditos_sbs
ORDER BY FECHA;

--MES CON MAYOR MOROSIDAD
SELECT TOP 1 FECHA, MOROSIDAD
FROM creditos_sbs
ORDER BY MOROSIDAD DESC;

--PROMEDIO DE MOROSIDAD POR ANIO
SELECT YEAR(FECHA) AS ANIO, AVG(MOROSIDAD) AS MOROSIDAD_PROMEDIO
FROM creditos_sbs
GROUP BY YEAR(FECHA)
ORDER BY MOROSIDAD_PROMEDIO;

--INDICADOR DE RIESGO
SELECT FECHA, MOROSIDAD,
	CASE 
		WHEN MOROSIDAD >= 6 THEN 'Critico'
		WHEN MOROSIDAD >= 4 THEN 'Alto'
		WHEN MOROSIDAD >= 2 THEN 'Moderado'
		ELSE 'Bajo' 	
	END AS NIVEL_RIESGO
FROM creditos_sbs;

-------------------------------------------------------------------------------------------
--SOLIDEZ BANCARIA
--RATIO PROMEDIO DE CAPITAL
SELECT AVG(RATIO_CAPITAL_GLOBAL) AS RATIO_PROMEDIO
FROM creditos_sbs;

--RENTABILIDAD PROMEDIO
SELECT 
	AVG(ROA) AS ROA_PROMEDIO,
	AVG(ROE) AS ROE_PROMEDIO
FROM creditos_sbs;

